before:
  hooks:
    - go mod download
    - go install github.com/gobuffalo/packr/v2/packr2
    - go generate ./...
    - packr2
builds:
- id: main-build
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm
    - arm64
  goarm:
    - 7
  ignore:
    - goos: darwin
      goarch: arm
    - goos: windows
      goarch: arm
    - goos: windows
      goarch: arm64
  ldflags:
    - -s -w -X main.build={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} 

release:
  prerelease: auto

dockers:
- image_templates:
  - dereulenspiegel/taplist:{{ .Version }}-amd64
  - dereulenspiegel/taplist:latest-amd64
  builds:
  - main-build
  binaries:
  - taplist
  dockerfile: Dockerfile
  goarch: amd64
  goos: linux
  extra_files:
  - frontend
  build_flag_templates:
  - "--platform=linux/amd64"
  - "--build-arg"
  - "ARCH=x86_64"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
- image_templates:
  - dereulenspiegel/taplist:{{ .Version }}-arm64
  - dereulenspiegel/taplist:latest-arm64
  builds:
  - main-build
  binaries:
  - taplist
  dockerfile: Dockerfile
  goos: linux
  goarch: arm64
  extra_files:
  - frontend
  build_flag_templates:
  - "--platform=linux/arm64"
  - "--build-arg"
  - "ARCH=arm64"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
- image_templates:
  - dereulenspiegel/taplist:{{ .Version }}-armv7
  - dereulenspiegel/taplist:latest-armv7
  builds:
  - main-build
  binaries:
  - taplist
  dockerfile: Dockerfile
  goos: linux
  goarch: arm
  goarm: 7
  extra_files:
  - frontend
  build_flag_templates:
  - "--platform=linux/arm/7"
  - "--build-arg"
  - "ARCH=arm_7"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
- name_template: dereulenspiegel/taplist:{{ .Version }}
  image_templates:
  - dereulenspiegel/taplist:{{ .Version }}-amd64
  - dereulenspiegel/taplist:{{ .Version }}-arm64
  - dereulenspiegel/taplist:{{ .Version }}-armv7
- name_template: dereulenspiegel/taplist:latest
  image_templates:
  - dereulenspiegel/taplist:latest-amd64
  - dereulenspiegel/taplist:latest-arm64
  - dereulenspiegel/taplist:latest-armv7

archives:
- replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
