FROM --platform=linux/amd64 alpine:3.12
RUN mkdir -p /opt/taplist
COPY taplist /opt/taplist/taplist
COPY frontend /opt/taplist/frontend
EXPOSE 9099
VOLUME ["/opt/taplist/data"]
ENTRYPOINT ["/opt/taplist/taplist"]
