version: 2.1
workflows:
  main:
    jobs:
    - build-frontend
    - release
        # Only run this job on git tag pushes
        #filters:
        #  branches:
        #    ignore: /.*/
        #  tags:
        #    only: /v[0-9]+(\.[0-9]+)*(-.*)*/
jobs:
  build-frontend:
    docker:
    - image: circleci/node
    steps:
    - checkout
    - restore_cache:
        name: Restore Yarn Package Cache
        keys:
        - yarn-packages-{{ checksum "frontend-src/yarn.lock" }}
    - run:
        name: Install Dependencies
        command: cd frontend-src && yarn install --immutable
    - run:
        name: Build frontend files
        command: cd frontend-src && yarn build
    - save_cache:
        name: Save Yarn Package Cache
        key: yarn-packages-{{ checksum "frontend-src/yarn.lock" }}
        paths:
          - ~/.cache/yarn
  release:
    docker:
    - image: circleci/golang:1.15
    steps:
    - checkout
    - run: curl -sL https://git.io/goreleaser | bash