version: 2.1
workflows:
  main:
    jobs:
    - build-frontend
    - snapshot:
        requires:
        - build-frontend
        # Only run this job on git tag pushes
        #
  release-flow:
    jobs:
    - build-frontend:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /v[0-9]+(\.[0-9]+)*(-.*)*/
    - release:
        requires:
        - build-frontend
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /v[0-9]+(\.[0-9]+)*(-.*)*/
jobs:
  build-frontend:
    docker:
    - image: circleci/node
    steps:
    - checkout
    - restore_cache:
        name: Restore Yarn Package Cache
        keys:
        - yarn-packages-{{ checksum "frontend-src/yarn.lock" }}
    - run:
        name: Install Dependencies
        command: cd frontend-src && yarn install --immutable
    - run:
        name: Build frontend files
        command: cd frontend-src && yarn build
    - save_cache:
        name: Save Yarn Package Cache
        key: yarn-packages-{{ checksum "frontend-src/yarn.lock" }}
        paths:
          - ~/.cache/yarn

  snapshot:
    docker:
    - image: circleci/golang:1.15
      auth:
        username: dereulenspiegel
        password: $DOCKERHUB_PASSWORD
    steps:
    - checkout
    - setup_remote_docker:
        version: 19.03.13
    - run: curl -sL https://git.io/goreleaser | bash -s -- --snapshot

  release:
    docker:
    - image: circleci/golang:1.15
      auth:
        username: dereulenspiegel
        password: $DOCKERHUB_PASSWORD
    steps:
    - checkout
    - setup_remote_docker:
        version: 19.03.13
    - run: |
        ssh remote-docker \<<EOF
          sudo bash -c 'echo "{\"experimental\": true}" > /etc/docker/daemon.json'
          sudo systemctl restart docker
        EOF
    - run: |
        mkdir -p ~/.docker && echo "{\"experimental\": true}" > ~/.docker/config.json
          
    - run: echo $DOCKERHUB_PASSWORD | docker login --username dereulenspiegel --password-stdin && curl -sL https://git.io/goreleaser | bash
