query {
  kegerator {
    serverVersion
    name
    taps {
      id
      number
      empty
      percentAvailable
      beer {
        id
        breweryName
        style
        name
        abv
        ibu
        colorEbc
        buGuRatio
        og
        fg
        gravityUnit
      }
    }
  }
}
